export interface CovidCountryStats {
  active: number,
  activePerOneMillion: number,
  cases: number,
  casesPerOneMillion: number,
  continent: string,
  country: string,
  countryInfo: {
    flag: string,
    iso2: string,
    iso3: string,
    lat: number,
    long: number,
    id: number,
  },
  critical: number,
  criticalPerOneMillion: number,
  deaths: number,
  deathsPerOneMillion: number,
  oneCasePerPeople: number,
  oneDeathPerPeople: number,
  oneTestPerPeople: number,
  population: number,
  recovered: number,
  recoveredPerOneMillion: number,
  tests: number,
  testsPerOneMillion: number,
  todayCases: number,
  todayDeaths: number,
  todayRecovered: number,
  updated: number,
}

export interface TotalWorld {
  active: number,
  cases: number,
  deaths: number,
  recovered: number,
  tests: number,
  todayCases: number,
  todayRecovered: number,
  todayDeaths: number,
}
